language: java
jdk:
- oraclejdk8
sudo: false
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- mvn package
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: gina.debeukelaer@ordina.be
  password:
    secure: GZPxlKmZ3MAjbCm01BT2bIZSvSpVSYBeb0ffoxsafJAVpXUZeQr5jEB9992tiGD86ZBQFu7wD1fcTgFvsFMBCO/8f9Nq1Ihntf/QRFsF5YAB7K2LBsT7kfQLEHkgzTDOWt0JCha4LmEX/7GpumhxOoR8Db4A/rVdI2B88L/I6Pmeqn0UZzLzYSTbMBHVoE9Ukw74Vw2M5cLQ/RR496M62qdizNQUC0+G85gb90lgwyOr5HxD68vMfHLgNVsAVvRwDCkuomyR/7/ie6D465t+7prW5XvsWSJcrcqDt5V195spXDnRIcZ3y5Gw491J01HomSpfTn5oXZEgedF8ogtEf4z8Ghp2C2d4PhQx/RyKaVmkzy6s42+HW1YJnIFXNdAOhsddPe3QhcMI/0J6V1wBc3CkyRfz63O5lP0Yg/Fp6INX4FwtrMtlSDISsNmfazi+jcnn5swNsewm7Yr7o3QbPNzPCr0R0VD1Pli9nZJWuVnUx0IvKoyPhqoUV1Z4wzP8nrn7pVYs/rPqOYf/9PKtElW2Th80J73leX/RgK5sYyyYRqr94FheLY4dnd1ZLwu0a9U0+GRh14ekyNj1Y10v3iPEJKWt2mbdmHX/eEPTlRRK925bF9xsnzC+1wfLT/GzfMi6qJ/gP0Njskc5/+ldn1bjyuI7pfKS8WQqVAc4rL8=
  organization: OrdinaBelgiumNV
  space: development
  on:
    repo: Ordineo/social-composite-service
    branch: master
notifications:
  slack:
    secure: ZjeAP0+63w3VPpulbS8w4f9cFLQUyDyNIX4sECcp+grceXFwF9CzeAuVAZTtJ7P5iFA2bzE/oiiiDuXPerK2e41YJLwikrXmGMwgxHvne0s968BaeVfMI2LzEu+CcAd2F8hVmb6pQ1d0pC+ygcl5tj9xJogUdNjTEmhj6ETvyku+Qh3Hb4FJTlC4WoiZP/csVURZVi0pgK88Z9aURvjjQWmS8QpSOEgEKoD9sxa/S6rEZe1GBZHETJJT7Hc9pOD+CNJxWdb4P7cHHMEPKA3Jx8p6KCPL7m63yTKb2QpLKPnmEeODY2+z461HDZGmVlbJ1Luoc0EwkFQAkvoqX1/GNJGDDuBcjbXJmGeYM/ZOyiDCxfJ+ztAdHtNNDY6DG1q4Yax0f8/UDeXH06La/DdesNHR6nGAXr6/kl508KY0F8y0HGgXvqa6ehSlp5tSMU2d3mJ1ZZMuCPU/XPMMIesp+Ew73SxKg0r+1jGCpHmNSd33jVVtPiSLmtCD2cLyWAnSC0Ul0oEbQAsMcNfuVIGRwCKTZk1lCawKFq3eLLD6I9tUVRbYWPfG5gXIcZhFxy7KhyxrYP9Z1LZmCaG2ZQRPwPXRhjwNXy+YdsxFMNhYF9kVXmfDWn+0nxcFWu2qgcHsGjq0G7XJ1K9x4We8/yl1FWU4AsrhifHgxqr/8M7NhJ4=
